GET http://localhost:3333/user

###

POST http://localhost:3333/user
Content-Type: application/json

 {
    "firstName": "Keil",
    "lastName": "Ricardo",
    "email": "keilricardo@gmail.com",
    "phoneNumber": "12345",
    "password": "12345",
    "gender": "Outro"
 }
###

PUT http://localhost:3333/user/Jaime
Content-Type: application/json

 {
    "username": "J.bEATRIZ",
    "password": "12345"
 }
###

DELETE  http://localhost:3333/user/Gustavo


